Shiten = {
  "101" => {
    "bank_bangou" => "1000",
    "shiten_bangou" => "101",
    "kanji_name" => "ふたご座支店",
    "nama_name" => "ふたご",
  },
  "102" => {
    "bank_bangou" => "1000",
    "shiten_bangou" => "102",
    "kanji_name" => "れちくる座支店",
    "nama_name" => "れちくる",
  },
  "103" => {
    "bank_bangou" => "1000",
    "shiten_bangou" => "103",
    "kanji_name" => "てんびん座支店",
    "nama_name" => "てんびん",
  },
  "104" => {
    "bank_bangou" => "1001",
    "shiten_bangou" => "104",
    "kanji_name" => "おひつじ座支店",
    "nama_name" => "おひつじ",
  },
  "105" => {
    "bank_bangou" => "1001",
    "shiten_bangou" => "105",
    "kanji_name" => "おうし座支店",
    "nama_name" => "おうし",
  },
  "106" => {
    "bank_bangou" => "1001",
    "shiten_bangou" => "106",
    "kanji_name" => "かに座支店",
    "nama_name" => "かに",
  },
  "107" => {
    "bank_bangou" => "1002",
    "shiten_bangou" => "107",
    "kanji_name" => "しし座支店",
    "nama_name" => "しし",
  },
  "108" => {
    "bank_bangou" => "1002",
    "shiten_bangou" => "108",
    "kanji_name" => "おとめ座支店",
    "nama_name" => "おとめ",
  },
  "109" => {
    "bank_bangou" => "1002",
    "shiten_bangou" => "109",
    "kanji_name" => "さそり座支店",
    "nama_name" => "さそり",
  },
  "110" => {
    "bank_bangou" => "1003",
    "shiten_bangou" => "110",
    "kanji_name" => "みずがめ座支店",
    "nama_name" => "みずがめ",
  },
  "111" => {
    "bank_bangou" => "1003",
    "shiten_bangou" => "111",
    "kanji_name" => "うお座支店",
    "nama_name" => "うお",
  },
  "112" => {
    "bank_bangou" => "1003",
    "shiten_bangou" => "112",
    "kanji_name" => "みなみのさんかく座支店",
    "nama_name" => "みなみのさんかく",
  },
  "113" => {
    "bank_bangou" => "1004",
    "shiten_bangou" => "113",
    "kanji_name" => "いて座支店",
    "nama_name" => "いて",
  },
  "114" => {
    "bank_bangou" => "1004",
    "shiten_bangou" => "114",
    "kanji_name" => "やぎ座支店",
    "nama_name" => "やぎ",
  },
  "115" => {
    "bank_bangou" => "1004",
    "shiten_bangou" => "115",
    "kanji_name" => "らしんばん座支店",
    "nama_name" => "らしんばん",
  },
  "116" => {
    "bank_bangou" => "1005",
    "shiten_bangou" => "116",
    "kanji_name" => "もねたカード",
    "nama_name" => "もねたカード",
  },
}
